Examples of Applicatios
lets look at some examples of ML tasks along with the techniques to tackle them.
Analyzing images of products on a production line to automatically classify them(this is image classification using Convolutional Networks
Detecting tumors in brain scans
This is sematic segmentation, where each pixel in the image is classified(as we want to detirmine the exact location and shape of tumors),typically using CNNs as well
Automatically classifying news articles 
"            " flagging offensive comments on discussion forms 
Summarizing long documents automatically 
Creating a chatbot or a personal assiatant 
forcating your companys revenue next year, based on many peformance metrics
making your app react to voice commands
detecting credit card fraud
segmenting clients based on their purchases so that you can designa different marketing startegy for each segment
Representing a complex, high dimentional dataset ina clear and insightful digram. this data vizualtion
recomeding a product a client may be intrested in based on paseed purches history 
building an intelligent bot for a game


Types of Machine Learning Systems
1 whether or not they are trained with human supervision(supervised, unsupervised, semisupervised, reinfroment learning
2 whether or not they cam learn incrementally on the fly(online vs batch learnign)
3 whether they work simply by comapring new data points to known data points, or instead by detecting patters in the tranning data and bulding perdictive model, much like scientist so( instance-based versus model-based learnring)
these criteria are not exclusive you can combine them any way you like

supervised/unsupervised Learning
ML systems can be classifed according to the ammount and type of supervision they get during training.
4 major categories supervised learning, unsupervised learning, semisupervised learning, and Reinforcement learning

SUPERVISED LEARNING 
in supervised learning. the traning set you fed the algo has the desired solution called labels
typical suoervised learining tasks are classification and to predict a target numeric value, such as a price of a car given a set of features called predictors(this sort of task is called regression.to train the system, you need to give it manyexamples of cars, including both their predictors and their labels(their prices)

IN ML an attribute is a data type(e.g., "mileage"), but a feature has several meanings, depending on context, but generally means an attribute plus its value(e.g, "mileage = 15,000") many people use the words attribute and feature interchangeably

note that some regression algos can be used for classification as well. and vice versa 
example regression is commonly used for classification, as it can output a value that corresponds to the probabity of belonging to a given class (e.g, 20% of being spam)

Supervised learning algo covered in this book
k-nearest Neighbors
linear regression
logistic regression
support vector machines
decision trees and random forest 
neural networks

Unsupervised Learning 
In Unsupervised Learning the training data is unlabeled. the system tries to learn without a teacher
Important unsupervised learning algos 
*Clustering 
-kmeans
-DBSCAN
-Hierarchical Cluster Analysis(HCA)
*Anomaly detection and novelty detection
-One-class svm
-Isolation Forest
*Visualization and dimensinality reduction
-Pricipal Component Analysis(pca)
-kernel PCA
-Locally Linear Embedding(LLE)
-t-Distributed Stochastic Neighbor Embedding(t-SNE)
*Association rule learning
-Apriori
-Eclat

A CLUSTERING algo: can try to detect similar groups. at no point do you tell the algo which group the names of groups or memebers of. it finds those connections without your help. if you use a HIRARCHICAL: clustering algorithm it may subdivide each group in smaller groups. this may help you better taget idividual groups

VIZUALIZATION algo are unsupervised learning algos: you feed them alot of complex and unlabeled data. and they output a 2d or 3d representation of your data that can easly be plotted. these algo try and preserve as much structure as they can(e.g, tying to keep separate clusters in the input space from overlapping in the visualization) so we may vetter understand how the data is orgazied and perhaps identify unsupectd patters

NOTE: a related task is dimensionality reduction, in which the goal is to simplify the data without losing too much info. one way to do this is to merge several correlated features into one. so the dimensionality reduction algo will merge them into one new feature this is called feature extraction 

TIP run a dimensionality reduction algo before feeding it to a secondary algo. for faster running less disk and memory space. and may add to performace 

ANOMALY DETECTION: detecting unusual credit card transactions to prevent fraud, catching manufacturing defects, or automatically removing outliers from a dataset before feeding it to another learning algo. the system is showend mostly normal instances during traning so it learns to recognize them: then, when it sees a ew instance, it can tell whether it looks like a normal one or whether it looks like an anomaly. as very simmilar task is NOVELTY DETECTION: it aims to detect tnew instances that look difrerent from  all instances in the traniing set(this requires a very clean training set, devoid of any insatcne you would like the algo to detect.

Association rule learning: the goal is to dig into large ammonts of data and discover intersting relations berween atributes

Semisupervised learning
Algos that can deal with partilly labeled data
most semi are a mix or super and non super

Reinforcement learning 
Uses a learning system called an agent and in this context can obesrve the enviorment, select and preform actions and get rewards in return or penalties in the form of negative rewards. it must then learn by itsself what is the best strategy, called a policy, to get the most rewad over time. a policy defines what action the agent can take when it is in a given situation

Batch and Online Learning 
another criterion to classify Machine Learning is whether or not systems can learn incrementally from a stream of incoming data
Batch learning: the system is incapable of learning incrementally: it must be trained using all the available data. this will generally take a lot of time and computing resources, so it is typically done offline. first the system is trained, and then it is lauched into production and runs without learning anymore; it just applies what it has learned. known as offline learning 
if the ammount of data is big enought it may make it impossinle to use a batch learning algo.

Online learning 
In online learning you train the system incrementally by feeding it data instances sequentially, either individually or in small groups called mini-batches. each learning step is fast and cheap, so the system can learn about new data on the fly. as it arrives

Online Learning is great for systems that recieve data as a continuous flow and need to adapt to change rapidly or autonomosly
also good if your working with limited computing resorces once the system has learned about new instsnces they may be delted 
online learning algos can also be used to train systems on huge datasets that cannit fit in one machines main memory (this is called out-of-core-learning)This algo loads part of the data, runs a training step on thst data, and repeat the process unitl it has run on all of the data. this is usually done offline so think of this as incremental learning 
The learning rate is one iportant parameter of online learning systems  is how fast they should adpt to changing data known as the learning rate

Bad data is a big challange with online learning is bad data that can gradually deline performane . bad data can come from a malfuntioning sensor on a robot or from someone spamming a search engine to try to rank high in search result. monitor the input data and react to abnormal sdata.( using an anomaly detection algo) promptly switch learning off and possiblt revert to a previously working state)

Instance-Based Verus Model-Based Learning 
another way to categozisse ml systems is by how they generalize. most ml tasks are about predictions. meaning that given a number of training examples, the system needs to be able to make good predictions for (generalize to) examples it has never seen before. good performance for the trainiing data is good but means little it cant perform well on new instances

the to main approaches to generalization Instance-based learning and model-based learning
Instance-based learning
the system learns the examples by heart, then generalizes to new cases by using a similarity measure to compara them to the learnd smaples 

Model Based Learning 
another way to generalize from a set of examples is to build a model of these examples and use that model to make predictions. 
this model has two model parameters 0.0 and 0.1. to find best performing values for the model you eed to specify a perfomance measure. you can either define a utility funtion that measures how good your model is, or you define a cost funtion that measures how bad it is. for linear regression problems, people typically use a cost funtion that measures the distnace between the linear models prediction and the training training examples; the objective is to minimize this distances 

This is where the linear regression algo comes in: you feed it your training examples an it finds the parameters that make the linear model fit best to your data - this is called training the model

confusingly the same word model can refer to a type of model. (e.g. linear regression) to a fully specified model architecture(e.g., Linear Regression with one input and one output. Model selection consists in choosing the type of model and fully specifying its architecture. Training a model means running an algo to find the model parameters that will make it best fit the training data( and hopefully make good predictions on new data)

if all went well, your model will make good predictions, if not, you may need to use more attributes , get more or better quality training data, or perhaps select a more powelful model

In short, since your main task is to select the algo and train it on some data, the two things that can go wrong are 1 bad algo 2 bad data
Insufficient Quantity of training data
everything data may be better than algo

Nonreprsentative Traing Data
to generalize well, it is crucial that your training data be representative of the new cases you want to generalize to 
can prove difficult if the sample is too small, you will have sampling noise, but even very large samples can be nonrepresentative if the method is flawed. called sampling bias


Poor-Quality Data
if some instances are clearly outliers, it may help to simply dsicard them to try to fix the erros manually

Irrelevant Features 
feature selection (selecting the most useful feature to train on among existing features)
feature extractiong(combining exiting features to make a more useful newone)
creating new features by gathering new data 

Overfitting the Training Data
the model performs well on the training data, but does not generalize well
overffitng happens when the model is too complex relative to the amount and noisiness of the training data-some posiblw soluions
simplify the model by selcting one with fewer paramaters(e.g., a linear model rather than a highdegree polynomialmodel)by reducing the number of attributes in the training data, or by constrainign the model,
Gather more data.
Reduce the noice in the trainign data(fix errors and remove outliers)

Constraining a model to make it simpler and redure the risk of overfitting is called regularization 
you want to find the right balance between fitting the training dat perfectly and keeping the model simple enough to ensure that it will generalize well

The ammount of regularization to apply during learing can be controlled by a hyperparameter. a hyperparameter is a paramemter of learning algos(not the model)as such it is not efected by the learning algo itself, it must be set prior to training and remains constant during training 
Tunung hyperparameters is an important part of building a machine learning system.

Underfitting the Training Data
uderfitting is the opposite of overfitting: it occurs when your model is too simple to learn the underlying structure of the data
Here the main options for fixing this problem
select a more powerful model, with more parameters
feed better features to the learning algo(feature engineering)
reduce the constraints on the model(e.g., reduce the regularization hyperparameter)

in a ML preject you gather data in a training set, and you feed the training set to a learning algo. if the algo is model-based, it tunes some parameters to fit the model to the training set, and then hopefully it will be able to make good predictions on new cases as well. if the algo is instance-based. it just learns to examples by heart and generalizes to new instances by using a similarity measure to compare them to the learned instances.

systems will not perform well if your training set is too small, or if the data is not representative, is noisy, or is polluted with irrelevant features(bullshit in bullshit out)your model needs to bee neither too simple nor too complex

Testing and Validating 
To test split your data into two sets: the training set and the test set. as these names imply, you train your model using the training set, and you test it using the test set
the error rate on new cases is called the generalization erroe( or out of sample error) and by evaluating your model on the test set,you get an estimate of this error. this value tells you how well your model will perfoem on instances is has never seen before.
If the training error is low (i.e., your model makes few mistakes on the training set)but the generalization error is high, it means that your model is overfitting the training data

a solution to model selection unsurtinanty is called holdout validation you hold out parts of the training set to evvaluate several candidate models and select the best one
cross validation
each model is evaluated once per validation, using many small validation sets. each model is evaluated once per validation set after the rest of the data. by averaging out all the evalutaions of a model, you get a much more eccurate measureof its performance

LOOk AT THE BIG PICTURE
Frame The Problem
knowing the objective is important because it will determine how you frame the problem, which algo you will select, which performance measure you will  use to evaluate your model and how much time you will spend atweaking it

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn.datasets import fetch_openml 
import matplotlib as mpl 
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

In [ ]:

from keras.layers import Dense
from keras.models import Sequential

In [ ]:
model = Sequential()
model.add(Dense(256, activation='relu',))
model.add

In [ ]:
mnist = fetch_openml('mnist_784', version=1)

In [ ]:
mnist.keys()

In [ ]:
X, y  = mnist['data'], mnist['target']

In [ ]:
display(X.shape)
display(y.shape)

In [ ]:
type(y)

In [ ]:
import matplotlib as mpl 
import matplotlib.pyplot as plt
import numpy as np


In [ ]:
some_digit = mnist['data'].loc[0]

In [ ]:
some_digit = some_digit.to_numpy()

In [ ]:
some_digit_image = some_digit.reshape(28, 28)

In [ ]:
plt.imshow(some_digit_image, cmap='binary')
plt.axis('off')
plt.show()

In [ ]:
y[0]

In [ ]:
y = y.astype(np.uint8)

In [ ]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [ ]:
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

In [ ]:
y_test_5

In [ ]:
from sklearn.linear_model import SGDClassifier 

In [ ]:
sdg_clf = SGDClassifier(random_state=22)
sdg_clf.fit(X_train, y_train_5)
sdg_clf.predict([some_digit])

In [ ]:
#X_train.reset_index

# Implementing Cross-Validation 

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
from sklearn.base import clone

In [ ]:
skfolds = StratifiedKFold(n_splits=3)

In [ ]:
skfolds.get_n_splits(X_train,y_train)

for train_index, test_index in skfolds.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X_train[train_index], X_test[test_index]
    y_train, y_test = y_train[train_index], y_test[test_index]

for train_index, test_index in skfolds.split(X_train, y_train_5):
    clone_clf = clone(sdg_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_trains_5[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train_5[test_index]




    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    n_correct = sum(y_pred == y_test_fold)
    print(n_correct / len(y_pred))

# Confusion Matrix 

In [ ]:
from sklearn.model_selection import cross_val_predict

In [ ]:
y_train_pred = cross_val_predict(sdg_clf, X_train, y_train_5, cv=3)
from sklearn.metrics import confusion_matrix 

In [ ]:
print(confusion_matrix(y_train_5, y_train_pred))

In [ ]:
y_train_perfect_predictions = y_train_5
print(confusion_matrix(y_train_5, y_train_perfect_predictions))

# Precison and Recall

# Decison Boundaries 

In [ ]:
from sklearn import datasets
import numpy as np
from sklearn.linear_model import LogisticRegression 
%matplotlib inline
import hvplot.pandas
import pandas as pd
import numpy as np
%matplotlib inline
from pylab import mpl, plt
from scipy.optimize import minimize
plt.style.use('seaborn')
mpl.rcParams['savefig.dpi'] = 300
mpl.rcParams['font.family'] = 'serif'
np.set_printoptions(precision=5, suppress=True,
                   formatter={'float': lambda x: f'{x:6.3f}'})

import datetime
import statsmodels.api as sm
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [ ]:
iris = datasets.load_iris()

In [ ]:
list(iris.keys())

In [ ]:
X = iris['data'][:, 3:]


In [ ]:
y = (iris['target'] == 2).astype(np.int)

In [ ]:
log_reg = LogisticRegression()

In [ ]:
log_reg.fit(X,y)

In [ ]:
X_new = np.linspace(0, 3, 1000).reshape(-1, 1)

In [ ]:
y_proba = log_reg.predict_proba(X_new)

In [ ]:
plt.plot(X_new, y_proba[:, 1], "g-", label='Iris virginica')
plt.plot(X_new, y_proba[:, 1], "b--", label='Not Iris virginica')

In [ ]:
log_reg.predict([[1.7], [1.5]])

In [ ]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import LinearSVC


In [ ]:
X, y = make_moons(n_samples=100, noise=0.15)
polynomial_svm_clf = Pipeline([
    ("poly_features", PolynomialFeatures(degree=3)),
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C=10, loss='hinge'))
])

In [ ]:
polynomial_svm_clf.fit(X,y)

In [ ]:

from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel='poly', degree=3, coef0=1, C=3))
    
])

In [ ]:
poly_kernel_svm_clf.fit(X, y)

In [ ]:
poly_kernel_svm_clf.score(X, y)

# Decison Trees

In [5]:
from sklearn.datasets import load_iris 
from sklearn.tree import DecisionTreeClassifier
from pathlib import Path

In [6]:
iris = load_iris()

In [7]:

X = iris.data[:, 2:]
y = iris.target

In [8]:
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [9]:
#!pip install pydot

In [10]:
from sklearn.tree import export_graphviz
from sklearn import tree
import pydot

In [11]:
export_graphviz(
    tree_clf,
    out_file=('iris_tree.dot'),
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)


tree.export_graphviz(tree_clf)
dotfile = StringIO()
pydot.graph_from_dot_data(dotfile.getvalue()).write_png("dtree2.png")

In [12]:

from sklearn import tree
plt.figure(figsize=(40,20))  # customize according to the size of your tree
_ = tree.plot_tree(tree_clf, feature_names = X_train.columns)
plt.show()

NameError: name 'plt' is not defined

In [13]:
tree_clf.predict_proba([[5, 1.5]])

array([[0.        , 0.90740741, 0.09259259]])

In [14]:
tree_clf.predict([[5, 1.5]])

array([1])

In [15]:
from sklearn.tree import DecisionTreeRegressor

In [16]:
tree_reg = DecisionTreeRegressor(max_depth=2)

In [17]:
tree_reg.fit(X, y)

DecisionTreeRegressor(max_depth=2)

# Ensamble Learning and Random Forests

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [19]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y)


In [21]:
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('rf', RandomForestClassifier()), ('svc', SVC())])

In [22]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

## Bagging and Pasting  in scikit-learn

In [23]:
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    max_samples=100, bootstrap=False, n_jobs=-1)
bag_clf.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), bootstrap=False,
                  max_samples=100, n_estimators=500, n_jobs=-1)

In [24]:
y_pred = bag_clf.predict(X_test)


In [25]:
y_pred[:5]

array([1, 2, 2, 2, 0])

In [26]:
pre = bag_clf.predict_proba(X_test)

In [27]:

pre[:5]

array([[0.   , 0.961, 0.039],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ]])

## Out-of-Bag Evaluation 

In [ ]:
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(max_depth=4), n_estimators=500,
    oob_score=True, bootstrap=True, n_jobs=-1)

In [ ]:
bag_clf.fit(X_train, y_train)


In [ ]:
bag_clf.oob_score_

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
y_pred = bag_clf.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
bag_clf.oob_decision_function_

In [ ]:
print(classification_report(y_test, y_pred))

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(X_train, y_train)

In [ ]:
y_pred_rf = rnd_clf.predict(X_test)

In [ ]:
y_pred_rf

In [ ]:
bad_clf = BaggingClassifier(
    DecisionTreeClassifier(splitter='random', max_leaf_nodes=1600),
    n_estimators=500, max_samples=1.0, bootstrap=True, n_jobs=-1)

In [ ]:
# feature importance 
from sklearn.datasets import load_wine

In [ ]:
# Boosting 
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2), n_estimators=200,
    algorithm='SAMME.R', learning_rate=0.5)
ada_clf.fit(X_train, y_train)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
tree_reg1 = DecisionTreeClassifier(max_depth=2)
tree_reg1.fit(X, y)

In [ ]:
y2 = y - tree_reg1.predict(X)
tree_reg2 = DecisionTreeClassifier(max_depth=2)
tree_reg2.fit(X, y2)

In [ ]:
y3 = y2 - tree_reg2.predict(X)
tree_reg3 = DecisionTreeClassifier(max_depth=2)
tree_reg3.fit(X, y3)

In [ ]:
#y_pred = sum([tree.predict(X_new) for tree in (tree_reg1, tree_reg2, tree_reg3)])

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=3, learning_rate=1.0)
g_pre= gbrt.fit(X, y)

In [ ]:
g_pre.predict(X_test)

In [ ]:
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.datasets import load_iris 
from sklearn.ensemble import GradientBoostingRegressor



In [ ]:
iris = load_iris()
X = iris.data[:, 2:]
y = iris.target

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y)

In [ ]:
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=120)
gbrt.fit(X_train, y_train)

In [ ]:
errors = [mean_squared_error(y_val, y_pred)
         for y_pred in gbrt.staged_predict(X_val)]
bst_n_esti = np.argmin(errors) + 1

In [ ]:
gbrt_best = GradientBoostingRegressor(max_depth=2, n_estimators=bst_n_esti)
gbrt_best.fit(X_train, y_train)

In [ ]:
gbrte = GradientBoostingRegressor(max_depth=3, warm_start=True)
min_val_error = float('inf')
error_going_up = 0
for n_estimators in range(1, 120):
    gbrte.n_estimators = n_estimators
    gbrte.fit(X_train, y_train)
    y_pred = gbrte.predict(X_val)
    val_error = mean_squared_error(y_val, y_pred)
    if val_error < min_val_error:
        min_val_error = val_error
        error_going_up = 0
    else:
        error_going_up += 1
        if error_going_up == 5:
            break

In [ ]:
#! pip install xgboost

In [ ]:
import xgboost

In [ ]:
xgb_reg = xgboost.XGBRegressor()
xgb_reg.fit(X_train, y_train)
y_pred = xgb_reg.predict(X_val)

In [ ]:
xgb_reg.fit(X_train, y_train,
           eval_set=[(X_val, y_val)], early_stopping_rounds=2)
y_pred = xgb_reg.predict(X_val)

## Dimensionality Reduction 

In [ ]:
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

In [ ]:
pca = PCA()
pca.fit(X_train)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

In [ ]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X_train)

In [ ]:
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X_train)
X_recovered = pca.inverse_transform(X_reduced)

In [ ]:
X_reduced[:5]


In [ ]:
X_recovered[:10]

In [ ]:
rnd_pca = PCA(n_components=154, svd_solver="randomized")
X_reduced = pca.fit_transform(X_train)


In [ ]:
X_reduced[:12]

In [ ]:
from sklearn.decomposition import IncrementalPCA

In [ ]:
n_batches = 100
inc_pca = IncrementalPCA(n_components=1)
for X_batch in np.array_split(X_train, n_batches):
    inc_pca.partial_fit(X_batch)
    
X_reduced = inc_pca.transform(X_train)
    
    

In [ ]:
X_reduced[:5]

In [ ]:
import pandas as pd

In [ ]:
#X_mm = np.memmap('DJIA (1).csv‪', dtype='float32', mode='readonly')

## Kernel PCA

In [ ]:
from sklearn.decomposition import KernelPCA
cash_flow = pd.read_csv('us-cashflow-annual-Copy1.csv',infer_datetime_format=True, parse_dates=True, delimiter=';')
cash_flow.rename(columns={'Report Date':'Date'}, inplace=True)
cash_flow.set_index('Date', inplace=True)


In [ ]:
rbf_pca = KernelPCA(n_components=2, kernel='rbf', gamma=0.04)
X_reduced = rbf_pca.fit_transform(X)

In [ ]:
X_reduced

In [ ]:
# selecting a kernel and tuning hyperparamets

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline


clf_jav = Pipeline([
    ('kpca', KernelPCA(n_components=2)),
    ('log_reg', LogisticRegression())
    
])

param_grid = [{
    "kpca__gamma":
    np.linspace(0.03, 0.05, 10),
    "kpca__kernel": ["rbf", "sigmoid"]
    
    
}]

grid_search = GridSearchCV(clf_jav, param_grid, cv=3)
grid_search.fit(X, y)

In [ ]:
print(grid_search.best_params_)

In [ ]:
rbf_pca=  KernelPCA(n_components = 2, kernel='rbf', gamma=0.0433,

                  fit_inverse_transform=True)
X_reduced = rbf_pca.fit_transform(X)
X_preimage = rbf_pca.inverse_transform(X_reduced)

In [ ]:
X_preimage[:10]

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(X, X_preimage)

## Unsupervised Learning Techniques

In [ ]:
from sklearn.datasets import load_iris
import numpy as np



In [ ]:
iris = load_iris()
list(iris.keys())


In [ ]:

X = iris.data

y = iris.target

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
k = 5
kmeans = KMeans(n_clusters=k)
y_pred = kmeans.fit(X)

In [ ]:
y_pred

In [ ]:
y_pred is kmeans.labels_

In [ ]:
kmeans.cluster_centers_

In [ ]:
X_new = np.array([[0, 2 ], [3, 2], [-3, 3], [-3, 2.5]])

In [ ]:
kmeans.predict(X)

In [ ]:
kmeans.transform(X)

In [ ]:
good_init = np.array([[-3, 3], [-3, 2], [-3, 2], [-1, 2], [0, 2]])

In [ ]:
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1)

In [ ]:
X

In [ ]:
# Accelerated K-Means and mini-batch K-Means

In [ ]:
from sklearn.cluster import MiniBatchKMeans
import os


In [ ]:
minibatch_kmeans = MiniBatchKMeans(n_clusters=5)

In [ ]:
intetia = minibatch_kmeans.fit(X)

In [ ]:
intetia.inertia_

In [ ]:
from sklearn.metrics import silhouette_score
silhouette_score(X,kmeans.labels_)

In [ ]:
from matplotlib.image import imread

In [ ]:
image = imread(os.path.join("green_sol.png"))

In [ ]:
X = image.reshape(-1, 3)
kmeans = KMeans(n_clusters=8).fit(X)
segmented_img = kmeans.cluster_centers_[kmeans.labels_]
segmented_img = segmented_img.reshape(image.shape)

In [ ]:
segmented_img

## Using Clustering for Preprocessing 

In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X_digits, y_digits = load_digits(return_X_y=True)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_digits, y_digits, test_size=0.2, random_state=14)

In [ ]:

scaler = StandardScaler()


X_scaler = scaler.fit(X_train)  



# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
# YOUR CODE HERE
X_test_scaled = X_scaler.transform(X_test)
# YOUR CODE HERE

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg = LogisticRegression(max_iter=7500)

In [ ]:
log_reg.fit(X_train, y_train)

In [ ]:
log_reg.score(X_test, y_test)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

In [ ]:
pipeline = Pipeline([
    ("kmeans", KMeans(n_clusters=50)),
    ("log_reg",LogisticRegression(max_iter=9000))
])
pipeline.fit(X_train, y_train)

In [ ]:
pipeline.score(X_test, y_test)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = dict(kmeans__n_clusters=range(2, 100))
grid_clf = GridSearchCV(pipeline, param_grid, cv=2, verbose=2)
grid_clf.fit(X_train, y_train)

In [ ]:
grid_clf.best_params_

### DBSCAN 

In [15]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
import numpy as np

In [3]:
X, y = make_moons(n_samples=1000, noise=0.05)
dbscan = DBSCAN(eps=0.05, min_samples=5)
dbscan.fit(X)

DBSCAN(eps=0.05)

In [5]:
dbscan.labels_[:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [6]:
len(dbscan.core_sample_indices_)

792

In [8]:
dbscan.core_sample_indices_[:15]

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

In [9]:
dbscan.components_

array([[-0.96798094,  0.18176469],
       [ 1.02201636,  0.23953738],
       [ 0.97373899,  0.39932331],
       ...,
       [-1.03458241,  0.03665786],
       [ 0.42244832,  0.84953114],
       [ 0.43222993,  0.85289226]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [16]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

In [17]:
knn.predict(X_new)

array([0, 1, 0, 3], dtype=int64)

In [18]:
knn.predict_proba(X_new)

array([[0.86, 0.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.7 , 0.  , 0.06, 0.  , 0.02, 0.22, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.92, 0.  , 0.  , 0.  , 0.08]])